### ISSUE TITLE
Different versions on Chrome web store and Github

### ISSUE THREAD

**Issue by easingthemes** [plussub/chrome-extension#1]
Hi,

Thanks for useful plugin.

Version on `Github` is not the same as on `Chrome web store`.
How to get latest version code?

Thanks

**Comment by easingthemes** [comment]
Initially it was `v1.9.9`, after `grunt` build I got `v.2`, now to figure out how to get latest `v2.32`

**Comment by ste-xx** [comment]
Hi,

The current process for assigning the version number is not well solved at the moment. 
As you have noticed, after a grunt build, the minor version will be updated. 
In the future, the version will be based on git tags. 

I'm going to search the current release version today
and tag it in git with "2.38".

Actually, the chrome store and github version is very different, because
in the current (github) version I have rebuilt/refactor a lot
(introduce Flux/Redux). 
Because of the (old) structure (3 Bower dependencies within 
from www.github.com/plussub) was it impracticable to make the changes in 
a branch. This should be easier in the future.

**Comment by easingthemes** [comment]
Great, thanks.
I have a lot of experience with Redux, so if you need any help ...

**Comment by ste-xx** [comment]
The currently released version:
tag 2.32 
Unfortunately the version vary in the manifest.json but otherwise everything is identical.

I would be pleased about support, unfortunately the project is not well documented at the moment. I will change this before the next release.

Redux:
plussub/chrome-extension uses the project plussub/core. It is integrated via Bower.

The Redux stuff is in core/redux and all Redux action types are in core/descriptor (for legacy reasons). 

I would appreciate feedback:)
